---
Name: buildsuffix-dev
Only:
  environment: 'dev'
---
BuiltAtRequirementsBackend:
  use_backend: false


---
Name: buildsuffix-test
Only:
  environment: 'test'
---
BuiltAtRequirementsBackend:
  use_backend: true


---
Name: buildsuffix-live
Only:
  environment: 'live'
---
BuiltAtRequirementsBackend:
  use_backend: true
